#!/usr/bin/env python3
"""
Collect commits from GitHub PR URLs whose commit message contains "generated by"
OR whose PR description contains "generated by" (then include all commits from that PR).

Input: CSV file containing PR URLs in a given column.

Features:
- Checkpoint/backup state file (JSON) saved after each PR
- Resume mode: skips already-processed PRs
- Incremental output CSV append

Usage:
  export GITHUB_TOKEN="ghp_..."   # recommended
  python collect_generated_by_commits_from_csv.py \
      --in prs.csv --col pr_url --out matches.csv --state state.json

Resume:
  python collect_generated_by_commits_from_csv.py \
      --in prs.csv --col pr_url --out matches.csv --state state.json --resume
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import time
from dataclasses import dataclass
from typing import Iterable, List, Optional, Set, Tuple
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Tuple, Dict


PHRASE_RE = re.compile(r"generated", re.IGNORECASE)


@dataclass(frozen=True)
class PRRef:
    owner: str
    repo: str
    number: int
    url: str

    @property
    def key(self) -> str:
        return f"{self.owner}/{self.repo}#{self.number}"


def parse_pr_url(url: str) -> Optional[PRRef]:
    """
    Parse URLs like:
      https://github.com/OWNER/REPO/pull/123
      https://github.com/OWNER/REPO/pull/123/files
      https://github.com/OWNER/REPO/pull/123?something
    """
    url = (url or "").strip()
    if not url or url.startswith("#"):
        return None
    try:
        parts = url.split("github.com/", 1)[1].split("/")
        owner = parts[0]
        repo = parts[1]
        if parts[2] != "pull":
            return None
        num_str = parts[3].split("?", 1)[0].split("#", 1)[0]
        number = int(num_str)
        return PRRef(owner=owner, repo=repo, number=number, url=url)
    except Exception:
        return None


def gh_session(token: Optional[str]) -> requests.Session:
    s = requests.Session()
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "collect-generated-by-commits-script",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    s.headers.update(headers)
    return s


def gh_paginate(s: requests.Session, url: str, params: Optional[dict] = None) -> Iterable[dict]:
    params = dict(params or {})
    params.setdefault("per_page", 100)

    while True:
        r = s.get(url, params=params, timeout=30)

        # basic rate-limit handling
        if r.status_code == 403 and "rate limit" in (r.text or "").lower():
            reset = r.headers.get("X-RateLimit-Reset")
            if reset and reset.isdigit():
                wait_s = max(0, int(reset) - int(time.time()) + 5)
                print(f"Rate limit hit. Sleeping {wait_s}s then retrying...", file=sys.stderr)
                time.sleep(wait_s)
                continue

        if r.status_code >= 400:
            raise RuntimeError(f"GitHub API error {r.status_code} for {url}: {r.text[:500]}")

        data = r.json()
        if isinstance(data, list):
            for item in data:
                yield item
        else:
            yield data

        link = r.headers.get("Link", "")
        next_url = None
        if link:
            for chunk in link.split(","):
                chunk = chunk.strip()
                if 'rel="next"' in chunk:
                    next_url = chunk.split(";", 1)[0].strip()[1:-1]
                    break
        if not next_url:
            break

        url = next_url
        params = None


def gh_get_json(s: requests.Session, url: str) -> dict:
    for item in gh_paginate(s, url):
        return item
    raise RuntimeError(f"Empty response for {url}")


def pr_contains_phrase(pr_body: Optional[str]) -> bool:
    return bool(pr_body) and bool(PHRASE_RE.search(pr_body))


def commit_message_contains_phrase(commit_message: str) -> bool:
    return bool(PHRASE_RE.search(commit_message or ""))


def collect_for_pr(s: requests.Session, pr: PRRef, sha_cache: Dict[str, dict], max_workers: int = 8) -> List[dict]:
    commits_api = f"https://api.github.com/repos/{pr.owner}/{pr.repo}/pulls/{pr.number}/commits"

    # 1) Scan PR commits and keep only matches
    matched: List[dict] = []
    for c in gh_paginate(s, commits_api):
        sha = c.get("sha")
        html_url = c.get("html_url")
        commit_obj = c.get("commit") or {}
        message = commit_obj.get("message") or ""
        author = (commit_obj.get("author") or {}).get("name") or ""
        author_date = (commit_obj.get("author") or {}).get("date") or ""

        if not commit_message_contains_phrase(message):
            continue

        matched.append(
            {
                "pr_url": pr.url,
                "owner": pr.owner,
                "repo": pr.repo,
                "pr_number": pr.number,
                "match_reason": "COMMIT_MESSAGE_MATCH",
                "sha": sha,
                "commit_url": html_url,
                "author": author,
                "author_date": author_date,
                "commit_message": message.replace("\n", "\\n"),
            }
        )

    if not matched:
        return []

    # 2) Fetch files changed for matched commits, in parallel, with caching
    def fetch_files_for_sha(sha: str) -> dict:
        if sha in sha_cache:
            return sha_cache[sha]

        filenames, details = get_commit_files_changed(s, pr.owner, pr.repo, sha)
        payload = {
            "files_changed_count": len(filenames),
            "files_changed": ";".join(filenames),
            "files_changed_detail": ";".join(details),
        }
        sha_cache[sha] = payload
        return payload

    # Thread pool
    futures = {}
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        for row in matched:
            sha = row["sha"]
            futures[ex.submit(fetch_files_for_sha, sha)] = sha

        # Collect results
        sha_to_files = {}
        for fut in as_completed(futures):
            sha = futures[fut]
            try:
                sha_to_files[sha] = fut.result()
            except Exception as e:
                # if commit detail fails, still output row with empty files
                sha_to_files[sha] = {
                    "files_changed_count": "",
                    "files_changed": "",
                    "files_changed_detail": "",
                }

    # 3) Merge into output rows
    out_rows: List[dict] = []
    for row in matched:
        files_info = sha_to_files.get(row["sha"], {})
        row.update(files_info)
        out_rows.append(row)

    return out_rows

def get_commit_files_changed(s: requests.Session, owner: str, repo: str, sha: str) -> Tuple[List[str], List[str]]:
    """
    Returns:
      - filenames list
      - detail list: filename|status|+add|-del
    """
    url = f"https://api.github.com/repos/{owner}/{repo}/commits/{sha}"
    data = gh_get_json(s, url)
    files = data.get("files") or []
    filenames: List[str] = []
    details: List[str] = []
    for f in files:
        fn = f.get("filename")
        if not fn:
            continue
        status = f.get("status", "")
        additions = f.get("additions", "")
        deletions = f.get("deletions", "")
        filenames.append(fn)
        details.append(f"{fn}|{status}|+{additions}|-{deletions}")
    return filenames, details

def load_state(path: str) -> dict:
    if not os.path.exists(path):
        return {"processed_prs": [], "errors": []}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def load_json(path: str, default):
    if not os.path.exists(path):
        return default
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def save_json_windows_safe(path: str, data) -> None:
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.flush()
        os.fsync(f.fileno())
    for _ in range(8):
        try:
            if os.path.exists(path):
                os.remove(path)
            os.rename(tmp, path)
            return
        except PermissionError:
            time.sleep(0.25)
    raise PermissionError(f"Could not replace file: {path}")



def save_state(path: str, state: dict) -> None:
    tmp = path + ".tmp"

    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2, ensure_ascii=False)
        f.flush()
        os.fsync(f.fileno())

    # Windows-safe replace
    for _ in range(5):  # retry a few times
        try:
            if os.path.exists(path):
                os.remove(path)
            os.rename(tmp, path)
            return
        except PermissionError:
            time.sleep(0.2)

    raise PermissionError(f"Could not replace state file: {path}")


def ensure_csv_header(path: str, fieldnames: List[str]) -> None:
    if os.path.exists(path) and os.path.getsize(path) > 0:
        return
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()


def append_rows_csv(path: str, fieldnames: List[str], rows: List[dict]) -> None:
    if not rows:
        return
    with open(path, "a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        for r in rows:
            w.writerow(r)


def read_pr_urls_from_csv(path: str, col: str) -> List[str]:
    urls: List[str] = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise RuntimeError("Input CSV has no header row.")
        if col not in reader.fieldnames:
            raise RuntimeError(f"Column '{col}' not found. Available columns: {reader.fieldnames}")
        for row in reader:
            u = (row.get(col) or "").strip()
            if u and not u.startswith("#"):
                urls.append(u)
    return urls


def main() -> int:

    ap = argparse.ArgumentParser()
    cache_path = "generated_by_commit_files_cache.json"
    sha_cache = load_json(cache_path, default={})

    input_csv = "AIDev_all_pull_request.csv"
    input_column = "html_url"
    #read token from txt file:
    token = None
    token_path = "git-token.txt"
    if os.path.exists(token_path):
        with open(token_path, "r", encoding="utf-8") as tf:
            token = tf.read().strip()

    ap.add_argument("--out", help="Output CSV path (appended incrementally)", default="generated_by_commits.csv")
    ap.add_argument("--state", help="State JSON path for checkpoint/resume", default="generated_by_commits_state.json")
    ap.add_argument("--resume", action="store_true", help="Resume from --state and keep appending to --out")

    args = ap.parse_args()

    pr_urls = read_pr_urls_from_csv(input_csv, input_column)

    pr_refs: List[PRRef] = []
    bad: List[str] = []
    for u in pr_urls:
        ref = parse_pr_url(u)
        if ref:
            pr_refs.append(ref)
        else:
            bad.append(u)

    if bad:
        print("Warning: could not parse these PR URLs (skipping):", file=sys.stderr)
        for u in bad[:50]:
            print(f"  - {u}", file=sys.stderr)
        if len(bad) > 50:
            print(f"  ... and {len(bad) - 50} more", file=sys.stderr)

    fieldnames = [
        "pr_url",
        "owner",
        "repo",
        "pr_number",
        "match_reason",
        "sha",
        "commit_url",
        "author",
        "author_date",
        "commit_message",
        "files_changed_count",
        "files_changed",
        "files_changed_detail",
    ]
    ensure_csv_header(args.out, fieldnames)

    state = load_state(args.state) if args.resume else {"processed_prs": [], "errors": []}
    processed: Set[str] = set(state.get("processed_prs", []))

    s = gh_session(token)

    found_total = 0
    processed_now = 0

    for pr in pr_refs:
        if args.resume and pr.key in processed:
            continue

        try:
            rows = collect_for_pr(s, pr, sha_cache, max_workers=8)

            append_rows_csv(args.out, fieldnames, rows)
            found_total += len(rows)

            processed.add(pr.key)
            state["processed_prs"] = sorted(processed)
            save_state(args.state, state)

            processed_now += 1
            print(f"[OK] {pr.key} | matches: {len(rows)}")
            save_json_windows_safe(cache_path, sha_cache)
        except Exception as e:
            err_msg = f"{pr.key} | {pr.url} | {type(e).__name__}: {e}"
            print(f"[ERR] {err_msg}", file=sys.stderr)
            state.setdefault("errors", []).append(err_msg)
            save_state(args.state, state)
            # NOTE: not marking as processed, so it retries on next resume run.

    print(f"Done. Processed now: {processed_now}. Total matches appended: {found_total}.")
    print(f"State saved at: {args.state}")
    print(f"Output CSV at: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
